name: "Run on container architecture"
branding:
  icon: "cpu"
  color: "green"
description: "Run commands in a specific container with a specific CPU architecture (armv6, armv7, aarch64, s390x, ppc64le)"
author: "Umberto Raimondi, Elijah Shaw-Rutschman, Abel Boldú"
inputs:
  arch:
    description: "CPU architecture: armv6, armv7, aarch64, s390x, ppc64le."
    required: false
    default: "aarch64"
  image:
    description: "Container image name and tag. Examples: nginx, alpine:latest, "
    required: true
    default: ""
  githubToken:
    description: 'Your GitHub token, used for caching Docker images in your project''s public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.'
    required: true
    default: ""
  env:
    description: "Environment variables to propagate to the container. YAML, but must begin with a | character. These variables will be available in both run and setup."
    required: false
    default: ""
  run:
    description: "Shell commands to execute in the container."
    required: true
  shell:
    description: "The shell to run commands with in the container. Default: /bin/sh"
    required: false
    default: "/bin/sh"
  dockerRunArgs:
    description: "Additional arguments to pass to docker run, such as volume mappings. See README for example usage."
    required: false
  setup:
    description: "Shell commands to execute on the host before running the container, such as creating directories for volume mappings. See README for example usage."
    required: false
    default: ""

runs:
  using: "node16"
  main: "src/container-on-arch.js"
