name: Build with Swift on armv7
on: [push, pull_request]

jobs:
  testactions_job:
    runs-on: ubuntu-18.04
    name: A job to test the multi architecture actions
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./
      with:
        arch: armv7
        distro: ubuntu18.04
        githubToken: ${{ github.token }}
        install: |
          apt-get update -q -y
          apt install -q -y libatomic1 libbsd0 clang libicu-dev libcurl4-nss-dev curl
          curl -L https://github.com/uraimo/buildSwiftOnARM/releases/download/5.0.3/swift-5.0.3-armv7-Ubuntu1804.tgz -o /root/swift-5.0.3-armv7-Ubuntu1804.tgz

        run: |
          cd /root
          tar xzf swift-5.0.3-armv7-Ubuntu1804.tgz
          echo "import Glibc;puts(\"Test!\");print(\"Test!!\")" > test.swift
          ./usr/bin/swiftc test.swift
          ./test
