name: Basic Example
on: [push, pull_request]

jobs:
  armv7_job:
    runs-on: ubuntu-latest
    name: Run on ubuntu kinetic armv7
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          image: ubuntu:22.10
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
